name: "cloud-resume-backend"

on:
  push:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - uses: terraform-linters/setup-tflint@v2
        name: setup tflint
        with:
          tflint_version: v0.39.2

      - name: init tflint
        run: tflint --init

      - name: run tflint
        run: tflint -f compact

  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          terraform_wrapper: false

      - name: terraform init
        working-directory: ${{ env.TERRAFORM_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform init

      - name: terraform fmt
        working-directory: ${{ env.TERRAFORM_DIR  }}
        run: terraform fmt -checkcc

      - name: terraform plan
        working-directory: ${{ env.TERRAFORM_DIR  }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform plan

      - name: terraform apply
        working-directory: ${{ env.TERRAFORM_DIR  }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
